HEADERS += \
    YAML/include/yaml-cpp/contrib/anchordict.h \
    YAML/include/yaml-cpp/contrib/graphbuilder.h \
    YAML/include/yaml-cpp/node/detail/bool_type.h \
    YAML/include/yaml-cpp/node/detail/impl.h \
    YAML/include/yaml-cpp/node/detail/iterator.h \
    YAML/include/yaml-cpp/node/detail/iterator_fwd.h \
    YAML/include/yaml-cpp/node/detail/memory.h \
    YAML/include/yaml-cpp/node/detail/node.h \
    YAML/include/yaml-cpp/node/detail/node_data.h \
    YAML/include/yaml-cpp/node/detail/node_iterator.h \
    YAML/include/yaml-cpp/node/detail/node_ref.h \
    YAML/include/yaml-cpp/node/convert.h \
    YAML/include/yaml-cpp/node/emit.h \
    YAML/include/yaml-cpp/node/impl.h \
    YAML/include/yaml-cpp/node/iterator.h \
    YAML/include/yaml-cpp/node/node.h \
    YAML/include/yaml-cpp/node/parse.h \
    YAML/include/yaml-cpp/node/ptr.h \
    YAML/include/yaml-cpp/node/type.h \
    YAML/include/yaml-cpp/anchor.h \
    YAML/include/yaml-cpp/binary.h \
    YAML/include/yaml-cpp/dll.h \
    YAML/include/yaml-cpp/emitfromevents.h \
    YAML/include/yaml-cpp/emitter.h \
    YAML/include/yaml-cpp/emitterdef.h \
    YAML/include/yaml-cpp/emittermanip.h \
    YAML/include/yaml-cpp/emitterstyle.h \
    YAML/include/yaml-cpp/eventhandler.h \
    YAML/include/yaml-cpp/exceptions.h \
    YAML/include/yaml-cpp/mark.h \
    YAML/include/yaml-cpp/noncopyable.h \
    YAML/include/yaml-cpp/null.h \
    YAML/include/yaml-cpp/ostream_wrapper.h \
    YAML/include/yaml-cpp/parser.h \
    YAML/include/yaml-cpp/stlemitter.h \
    YAML/include/yaml-cpp/traits.h \
    YAML/include/yaml-cpp/yaml.h \
    YAML/src/contrib/graphbuilderadapter.h \
    YAML/src/collectionstack.h \
    YAML/src/directives.h \
    YAML/src/emitterstate.h \
    YAML/src/emitterutils.h \
    YAML/src/exp.h \
    YAML/src/indentation.h \
    YAML/src/nodebuilder.h \
    YAML/src/nodeevents.h \
    YAML/src/ptr_stack.h \
    YAML/src/ptr_vector.h \
    YAML/src/regex_yaml.h \
    YAML/src/regeximpl.h \
    YAML/src/scanner.h \
    YAML/src/scanscalar.h \
    YAML/src/scantag.h \
    YAML/src/setting.h \
    YAML/src/singledocparser.h \
    YAML/src/stream.h \
    YAML/src/streamcharsource.h \
    YAML/src/stringsource.h \
    YAML/src/tag.h \
    YAML/src/token.h

SOURCES += \
    YAML/src/contrib/graphbuilder.cpp \
    YAML/src/contrib/graphbuilderadapter.cpp \
    YAML/src/binary.cpp \
    YAML/src/convert.cpp \
    YAML/src/directives.cpp \
    YAML/src/emit.cpp \
    YAML/src/emitfromevents.cpp \
    YAML/src/emitter.cpp \
    YAML/src/emitterstate.cpp \
    YAML/src/emitterutils.cpp \
    YAML/src/exp.cpp \
    YAML/src/memory.cpp \
    YAML/src/node_data.cpp \
    YAML/src/nodebuilder.cpp \
    YAML/src/nodeevents.cpp \
    YAML/src/null.cpp \
    YAML/src/ostream_wrapper.cpp \
    YAML/src/parse.cpp \
    YAML/src/parser.cpp \
    YAML/src/regex_yaml.cpp \
    YAML/src/scanner.cpp \
    YAML/src/scanscalar.cpp \
    YAML/src/scantag.cpp \
    YAML/src/scantoken.cpp \
    YAML/src/simplekey.cpp \
    YAML/src/singledocparser.cpp \
    YAML/src/stream.cpp \
    YAML/src/tag.cpp \
    $$PWD/src/node_yaml.cpp
  #  YAML-build/CMakeFiles/3.3.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
  #  YAML-build/CMakeFiles/feature_tests.cxx \
  #  YAML-build/CMakeFiles/3.3.2/CompilerIdC/CMakeCCompilerId.c

