name: gemsfits

dependencies:
  - cmake>=3.13
  - ninja
  - clcache  # [win]
  - ccache  # [unix]
  - gxx_linux-64>=9.4.0  # [linux]
  - clangxx_osx-64  # [osx]
  - vs2019_win-64  # [win]
  - git
  - nlohmann_json
  - spdlog
  - yaml-cpp
  - libgomp # [linux]
  - boost=1.83.0
  - armadillo
  - nlopt  # [win]
  - qt6-main
  - qt6-charts
  - mesa-libgl-devel-cos7-x86_64 # [unix]

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
