name: gemsfits

dependencies:
  - cmake>=3.13
  - ninja
  - clcache  # [win]
  - ccache  # [unix]
  - gxx_linux-64>=9.4.0  # [linux]
  - clangxx_osx-64  # [osx]
  - vs2019_win-64  # [win]
  - git
  - nlohmann_json
  - spdlog
  - yaml-cpp
  #- nlopt
  - libgomp
  - boost=1.83.0
  - armadillo
  #- gems3k>=4.3.6
  #- thermofun>=0.4.3
  - qt>=5.12.5
  - mesalib
  - mesa-libgl-cos6-x86_64 # [linux]
  - libselinux-cos6-x86_64 # [linux]
  - libxxf86vm-cos6-x86_64 # [linux]
  - xorg-libxext # [linux]
  - xorg-libxau # [linux]
  - xorg-libxdamage # [linux]


environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
