name: gemsfits

dependencies:
  - cmake>=3.16
  - ninja
  #- clcache  # [win]
  - ccache  # [unix]
  - gxx_linux-64>=9.4.0  # [linux]
  - clangxx_osx-64  # [osx]
  #- vs2019_win-64  # [win]
  - git
  - nlohmann_json
  - spdlog=1.11.0
  - yaml-cpp
  - libgomp # [linux]
  - boost-cpp=1.83.0
  - armadillo # [unix]
  - nlopt
  - qt6-main
  - qt6-charts
  #- qt-main=5.15.8
  - mesa-libgl-devel-cos7-x86_64 # [unix]

environment:

  LD_LIBRARY_PATH:                                                   # [unix]
    - {{ root }}/artifacts/lib                                       # [unix]

  PATH:                                                              # [win]
    - {{ root }}\artifacts\bin                                       # [win]
