name: gemsfits

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - git
  - gcc_linux-64  # [linux] 
  - gxx_linux-64  # [linux] 
  - sysroot_linux-64 # [linux] 
  - make  # [unix]
  - ninja
  - 7zip  # [win]
  - zlib
  - gems3k>=4.4.2
  - yaml-cpp
  - libgomp # [linux]
  - boost-cpp
  - armadillo
  - libblas
  - liblapack
  - nlopt
  - mesa-libgl-devel-conda-x86_64 # [unix]
  - qt6-main=6.8.2
  - qt6-charts=6.8.2
  - python>=3.7
  - pytest
