#pragma once

#define GEMSFITS_VERSION "2.0.0"
#define GEMSFITS_VERSION_HASH "b0ad5063"
#define GEMSFITS_GIT_BRANCH "master"
#define GEMSFITS_OSX "Linux"
#define GEMSFITS_COMPILER_ID "GNU"
#define GEMSFITS_COMPILER_VERSION "13.3.0"
#define GEMSFITS_QT_VERSION "6.10.2"
